### PR TITLE
Introduce mocha + chai and implement some tests with it

### PR DESCRIPTION
**Pull request by gvko**

### CODE REVIEW

**Comment by adrian-gierakowski** [comment]
Any reason not to keep using jest?

**Comment by gvko** [comment]
> Any reason not to keep using jest?

@adrian-gierakowski , yes, it runs very slowly.
Builds are running 10+ min cuz of slow tests. 
Same case when we run the tests locally. I've made some isolated test suites comparison and with `mocha` they run 20+ times faster than with `jest` :man_shrugging:

**Comment by adrian-gierakowski** [comment]
> Builds are running 10+ min cuz of slow tests.
> Same case when we run the tests locally. I've made some isolated test suites comparison and with `mocha` they run 20+ times faster than with `jest`

Jest runs each test file in a sandbox (in a worker process), which brings a lot of benefits (like ability to run tests in parallel), but which also means any imports and setup code will run from scratch for each test file which makes the startup time a bit slower. Most of the time this is not a problem but I believe the massive slowdown compared to mocha you are seeing might be caused by repeated initialisation of some web3 related code (mocha would only run this once, while jest does once per test file). I wonder if we could identify the code which is slowing the tests down and find a solution which would allow us to keep using jest?

**Comment by adrian-gierakowski** [comment]
there is no way to share modules/instances between tests, not event within a single worker

see:
https://github.com/facebook/jest/issues/7184#issuecomment-730801495
https://github.com/facebook/jest/issues/8708

I believe there is a hack which allows to [share strings from global setup to tests via `process.env`](https://github.com/facebook/jest/issues/7184#issuecomment-746436538), but I don't think that would help here

2 possible solutions:
1. mock the stuff that takes so long to initialise in most tests
2. run tests in a single worker by creating in index file which requires all individual test files and passing that index file as an argument to jest (instead of letting it find all tests files)

**Pull request closed without merging**
